// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: gatica/middleearth/v1/people.proto

/* eslint-disable */

export const protobufPackage = 'gatica.middleearth.v1'

export enum People {
  PEOPLE_UNSPECIFIED = 0,
  PEOPLE_OTHER = 1,
  PEOPLE_VALAR = 2,
  PEOPLE_MAIAR = 3,
  PEOPLE_ELVES = 4,
  PEOPLE_MEN = 5,
  PEOPLE_DWARVES = 6,
  PEOPLE_HOBBITS = 7,
  PEOPLE_ENTS = 8,
  PEOPLE_ORCS = 9,
  PEOPLE_TROLLS = 10,
  PEOPLE_TROLLS212 = 11,
  UNRECOGNIZED = -1,
}

export function peopleFromJSON(object: any): People {
  switch (object) {
    case 0:
    case 'PEOPLE_UNSPECIFIED':
      return People.PEOPLE_UNSPECIFIED
    case 1:
    case 'PEOPLE_OTHER':
      return People.PEOPLE_OTHER
    case 2:
    case 'PEOPLE_VALAR':
      return People.PEOPLE_VALAR
    case 3:
    case 'PEOPLE_MAIAR':
      return People.PEOPLE_MAIAR
    case 4:
    case 'PEOPLE_ELVES':
      return People.PEOPLE_ELVES
    case 5:
    case 'PEOPLE_MEN':
      return People.PEOPLE_MEN
    case 6:
    case 'PEOPLE_DWARVES':
      return People.PEOPLE_DWARVES
    case 7:
    case 'PEOPLE_HOBBITS':
      return People.PEOPLE_HOBBITS
    case 8:
    case 'PEOPLE_ENTS':
      return People.PEOPLE_ENTS
    case 9:
    case 'PEOPLE_ORCS':
      return People.PEOPLE_ORCS
    case 10:
    case 'PEOPLE_TROLLS':
      return People.PEOPLE_TROLLS
    case 11:
    case 'PEOPLE_TROLLS212':
      return People.PEOPLE_TROLLS212
    case -1:
    case 'UNRECOGNIZED':
    default:
      return People.UNRECOGNIZED
  }
}

export function peopleToJSON(object: People): string {
  switch (object) {
    case People.PEOPLE_UNSPECIFIED:
      return 'PEOPLE_UNSPECIFIED'
    case People.PEOPLE_OTHER:
      return 'PEOPLE_OTHER'
    case People.PEOPLE_VALAR:
      return 'PEOPLE_VALAR'
    case People.PEOPLE_MAIAR:
      return 'PEOPLE_MAIAR'
    case People.PEOPLE_ELVES:
      return 'PEOPLE_ELVES'
    case People.PEOPLE_MEN:
      return 'PEOPLE_MEN'
    case People.PEOPLE_DWARVES:
      return 'PEOPLE_DWARVES'
    case People.PEOPLE_HOBBITS:
      return 'PEOPLE_HOBBITS'
    case People.PEOPLE_ENTS:
      return 'PEOPLE_ENTS'
    case People.PEOPLE_ORCS:
      return 'PEOPLE_ORCS'
    case People.PEOPLE_TROLLS:
      return 'PEOPLE_TROLLS'
    case People.PEOPLE_TROLLS212:
      return 'PEOPLE_TROLLS212'
    case People.UNRECOGNIZED:
    default:
      return 'UNRECOGNIZED'
  }
}
